# Use postgres/example user/password credentials
version: '3.1'

services:
  dbAuth:
    container_name: EnocaPostgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: CompanyDB
    ports:
      - "5432:5432"